void animationKUB(int number)
{
    int x=1;
    while (number=1)
    {
    printf("             \n");
    printf("             \n");
    printf("             \n");
    printf("             \n");
    printf("             \n");
    printf("      #      \n");
    printf("             \n");
    printf("             \n");
    printf("             \n");
    printf("             \n");
    printf("             \n");
    system("cls");
    printf("             \n");
    printf("             \n");
    printf("             \n");
    printf("             \n");
    printf("     ###     \n");
    printf("     ###     \n");
    printf("     ###     \n");
    printf("             \n");
    printf("             \n");
    printf("             \n");
    printf("             \n");
    system("cls");
    printf("             \n");
    printf("             \n");
    printf("             \n");
    printf("    #####    \n");
    printf("    #####    \n");
    printf("    #####    \n");
    printf("    #####    \n");
    printf("    #####    \n");
    printf("             \n");
    printf("             \n");
    printf("             \n");
    system("cls");
    printf("             \n");
    printf("             \n");
    printf("   #######   \n");
    printf("   #######   \n");
    printf("   #######   \n");
    printf("   #######   \n");
    printf("   #######   \n");
    printf("   #######   \n");
    printf("   #######   \n");
    printf("             \n");
    printf("             \n");
    system("cls");
    printf("             \n");
    printf("  #########  \n");
    printf("  #########  \n");
    printf("  #########  \n");
    printf("  #########  \n");
    printf("  #########  \n");
    printf("  #########  \n");
    printf("  #########  \n");
    printf("  #########  \n");
    printf("  #########  \n");
    printf("             \n");
    system("cls");
    printf(" ########### \n");
    printf(" ########### \n");
    printf(" ########### \n");
    printf(" ########### \n");
    printf(" ########### \n");
    printf(" ########### \n");
    printf(" ########### \n");
    printf(" ########### \n");
    printf(" ########### \n");
    printf(" ########### \n");
    printf(" ########### \n");
    system("cls");
    printf("             \n");
    printf("  #########  \n");
    printf("  #########  \n");
    printf("  #########  \n");
    printf("  #########  \n");
    printf("  #########  \n");
    printf("  #########  \n");
    printf("  #########  \n");
    printf("  #########  \n");
    printf("  #########  \n");
    printf("             \n");
    system("cls");
    printf("             \n");
    printf("             \n");
    printf("   #######   \n");
    printf("   #######   \n");
    printf("   #######   \n");
    printf("   #######   \n");
    printf("   #######   \n");
    printf("   #######   \n");
    printf("   #######   \n");
    printf("             \n");
    printf("             \n");
    system("cls");
    printf("             \n");
    printf("             \n");
    printf("             \n");
    printf("    #####    \n");
    printf("    #####    \n");
    printf("    #####    \n");
    printf("    #####    \n");
    printf("    #####    \n");
    printf("             \n");
    printf("             \n");
    printf("             \n");
    system("cls");
    printf("             \n");
    printf("             \n");
    printf("             \n");
    printf("             \n");
    printf("     ###     \n");
    printf("     ###     \n");
    printf("     ###     \n");
    printf("             \n");
    printf("             \n");
    printf("             \n");
    printf("             \n");
    system("cls");
    printf("             \n");
    printf("             \n");
    printf("             \n");
    printf("             \n");
    printf("             \n");
    printf("      #      \n");
    printf("             \n");
    printf("             \n");
    printf("             \n");
    printf("             \n");
    printf("             \n");
    system("cls");
    --number;
   }
}
